CIRCUITPY_WIFI_SSID = "<SSID>"
CIRCUITPY_WIFI_PASSWORD = "<PASSWORD>"

511_API_KEY = "<API_KEY>"
511_TRANSIT_AGENCY = "SF"
511_TRANSIT_DIRECTIONS = "OB"
511_TRANSIT_ROUTE_CODES = "K,N"
511_TRANSIT_STOP_CODE = "16995"
